[directory]
truncation_symbol = ".../"

[sudo]
disabled = false

[battery]
full_symbol = "🔋"
charging_symbol = "🔌"
discharging_symbol = "⚡"

[[battery.display]]
threshold = 30
style = "bold red"

[cmd_duration]
min_time = 10_000  # Show command duration over 10,000 milliseconds (=10 sec)
format = " took [$duration]($style)"

[git_branch]
format = " [$symbol$branch]($style) "
style = "bold yellow"

[git_status]
ahead = "⇡×${count}"
behind = "⇣×${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
format = "$all_status$ahead_behind "

[package]
disabled = true
