-- disable netrw at the very start of your init.lua (strongly advised)
-- vim.g.loaded = 1
-- vim.g.loaded_netrwPlugin = 1

-- local function toggle_replace()
-- 	local view = require("nvim-tree.view")
-- 	if view.is_visible() then
-- 		view.close()
-- 	else
-- 		require("nvim-tree").open_replacing_current_buffer()
-- 	end
-- end

-- OR setup with some options
-- require("nvim-tree").setup({
-- 	view = {
-- 		mappings = {
-- 			list = {
-- 				{ key = "h", action = "close_node" },
-- 				{ key = "n", action = "create" },
-- 				{ key = "l", action = toggle_replace },
-- 				{ key = "<cr>", action = "edit_in_place" },
-- 			},
-- 		},
-- 	},
-- 	disable_netrw = true,
-- 	hijack_netrw = true,
-- 	renderer = {
-- 		icons = {
-- 			glyphs = {
-- 				folder = {
-- 					arrow_closed = "❯",
-- 				},
-- 			},
-- 		},
-- 	},
-- 	actions = {
-- 		open_file = {
-- 			window_picker = {
-- 				enable = false,
-- 			},
-- 		},
-- 	},
-- })
