[bar.default]
start = ["launcher", "workspaces", "sysmon", "ram", "temp", "active_window"]
center = ["clock", "media"]
end = [
  "tray",
  "notifications",
  "clipboard",
  "network",
  "davemhammer/tailscale:status",
  "bluetooth",
  "volume",
  "brightness",
  "battery",
  "control-center",
  "session",
]
widget_spacing = 10

[widget.clock]
anchor = true
format = "{:%-I:%M %p · %a, %b %-d}"

[widget.media]
hide_when_no_media = true
show_progress = true

[widget.network]
show_label = false

[widget.ram]
label_show_units = false
show_value = false

[widget.sysmon]
show_value = false

[widget.temp]
show_value = false
