[bar.default]
end = [
  "media",
  "tray",
  "notifications",
  "clipboard",
  "network",
  "davemhammer/tailscale:status",
  "bluetooth",
  "volume",
  "brightness",
  "battery",
  "control-center",
  "session",
]
